### ISSUE TITLE
Ditdefender triggered by some code on the page

### ISSUE THREAD

**Issue by kombogdan** [NoAgenda/website#71]
Antivirus Bitdefender Total Security 26.0.33 blocks some parts of the website, identifying it as "Infected web page". Does not appear to affect the functionality. See the screenshot for more info.
![Screenshot](https://user-images.githubusercontent.com/24945951/219403184-1a83ed64-c889-4242-8ff1-d7949fdead41.png)

**Comment by codedmonkey** [comment]
It looks like it triggers on the analytics module, which is only used as a high-end view counter.
